### PR TITLE
Add Travis build for publishing new versions

### PR DESCRIPTION
**Pull request by gyoshev**
Thanks for creating this bundle, it is pretty handy :tada: 

This PR adds a Travis build to make publishing new bundle versions automatic. If [set up as a cron job](https://docs.travis-ci.com/user/cron-jobs/) and [provided with an NPM token](https://docs.travis-ci.com/user/deployment/npm/#NPM-auth-token), this build should be able to track the RxJs releases without supervision.

### CODE REVIEW

**Comment by kylecordes** [comment]
@gyoshev Thank you, this is an excellent idea. But, I tried experimenting with it locally. I found that does not work because the "inc version" script only ever moves one version passed the committed package.json file version.

To get things up to date, I manually stepped through all the versions since then, and published each one, committed each one. So you can now get everything up to the most current 5.4.3 this way.

Do you have an idea on how to make this automatic publish mechanism work, for every version? Here is my idea:

Rather than look at the current version in the package file, instead it could query the NPM repository to find out the most recent version of rxjs-system-bundle verses the most recent version of rxjs. Then publish a new version only if they don't match. In this way, we could simply run it on Cron as you described and it would automatically publish every version.

I think this will be pretty easy to implement, using `api-npm` which is already used by the inc version script. If you try it, I will test it and hopefully merge it!

**Comment by gyoshev** [comment]
Your idea seems good, I'll give it a try.

When I tested the inc_version script I was left with the wrong impression that it will publish a new version with each subsequent build -- however that is only true if the package.json is pushed to the repo after a successful build.

**Comment by kylecordes** [comment]
I like this very much. I see only one remaining problem. You can see it in the Travis output linked above, or here:

https://travis-ci.org/OasisDigital/rxjs-system-bundle/builds/274951711

The build shows up is failing, if the published bundle is already up to date. So if I set it to run on Cron every day, it will show a failing build almost every day, and that is not fun.

What do you think of making it so that, if the published bundle is already 100% up-to-date, we consider this "success", exit code 0, so that the build shows up as success?

**Comment by gyoshev** [comment]
Yes, I was thinking about that. This way the build will only fail if there are other reasons. I'll push this in a bit.

**Comment by gyoshev** [comment]
Hooray, a green build! Adding the encrypted token to `.travis.yml` and setting up the cron job should set the trap for the next rxjs release :smile:

**Comment by kylecordes** [comment]
I merged this. Still TODO: provide the token etc. I haven't done that with Travis before, digging in to understand it.

**Comment by kylecordes** [comment]
Done:

* A tiny bit more logic to only proceed with the publishing, if the build found that the version is out of date
* put in the encrypted API key
* added the daily Cron

https://github.com/OasisDigital/rxjs-system-bundle/commit/3d5e287961d8eab47c2a0e1358f77ce172501bc1

Now, we wait to see if it works the next time an upstream version is published!

**Comment by gyoshev** [comment]
Great! Fingers crossed :crossed_fingers:

**Pull request merged**
